<a href="https://colab.research.google.com/github/khajaowais/ColabPrimerSS2021/blob/main/TensorFlow_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sources:
* https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/TensorFlow/Basics/tutorial2-tensorbasics.py
* https://www.youtube.com/watch?v=tPYj3fFJGjk
* https://www.tensorflow.org/guide/tensor


#TensorFlow 2.0 Introduction
In this notebook you will be given an interactive introduction to TensorFlow 2.0. We will walk through the following topics within the TensorFlow module:

- TensorFlow Install and Setup
- Representing Tensors
- Tensor Shape and Rank
- Types of Tensors
- Tensor Operations


If you'd like to follow along without installing TensorFlow on your machine you can use **Google Colaboratory**. Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.


# What is TensorFlow?
Tensors are the heart of TensorFlow. Tensors can be thought of as multidimensional arrays. 

TensorFlow makes it convenient to define operations on these tensors, such as matrix-vector multiplication, and execute them efficiently, regardless of the underlying hardware.

TensorFlow also has an automatic differentiation engine. This allows us to compute the gradients of differentiable functions, assuming we can express them using TensorFlow primitives.

These two aspects together have made TensorFlow popular for training neural networks:
* We can define neural network parameters as a list of tensors.
* We can define a loss using TensorFlow primitives and tensors.
* We can compute the gradients of a loss with respect to the neural network parameters, using the automatic differentiation engine.
* We can update the parameters using an optimization scheme (such as SGD).

TensorFlow makes it easy to do all of this! 

##Installing TensorFlow
To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```

If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: https://www.tensorflow.org/install/gpu 
```console
pip install tensorflow-gpu
```

##Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It shouldn't surprise you that tensors are a fundemental aspect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program.

<!-- Each tensor represents a partially defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated. -->

Each tensor has a data type and a shape. 

**Data Types**: float32, int32, string, and so on.

**Shape**: Represents the dimension of data.

Just like vectors and matrices, tensors can have operations applied to them: addition, subtraction, dot product, cross product and so on.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how TensorFlow represents data and how you can manipulate this data.


###Creating Tensors
Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

In [ ]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


###Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 

Now we'll create some tensors of higher degrees/ranks.

In [ ]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

**To determine the rank** of a tensor we can call the following method.

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

The rank of a tensor is direclty related to the deepest level of nested lists. You can see in the first example ```["Test"]``` is a rank 1 tensor as the deepest level of nesting is 1. 
Where in the second example ```[["test", "ok"], ["test", "yes"]]``` is a rank 2 tensor as the deepest level of nesting is 2.

###Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

###Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [ ]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
                                                                             
# The number of elements in the reshaped tensor MUST match the number in the original
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


###Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [ ]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [ ]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


###Types of Tensors
These are the diffent types of tensors.
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of ```Variable``` all these tensors are immutable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor, such as to repre



#Tensor Operations

Below, we describe some additional operations that can be performed with tensors.


In [ ]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# Identity Matrix
x = tf.eye(3)
print(x)

# Matrix of ones
x = tf.ones((4, 3))
print(x)

# Matrix of zeros
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [ ]:
# Sampling from a uniform distribution (https://en.wikipedia.org/wiki/Continuous_uniform_distribution)
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

# Sampling from a normal distribution (https://en.wikipedia.org/wiki/Normal_distribution)
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

# Constructing a tensor with range limits and step values
x = tf.range(9)
print(x)

x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor(
[[0.43221462 0.11768067]
 [0.53404176 0.094203  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.881812    0.13387021 -0.4404107 ]
 [ 0.36322856  1.740028   -0.6820432 ]
 [-1.4119354  -0.5583211  -0.3960701 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
# Changing the data type of a tensor
# Supported dtypes : tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool
print(tf.cast(x, dtype=tf.float64))

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float64)


In [ ]:
# Mathematical Operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# Two ways of addition
z = tf.add(x, y)
z = x + y
print(f"Adding {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

# Two ways of subtraction
z = tf.subtract(x, y)
z = x - y
print(f"Subtracting {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

# Two ways of element-wise division
z = tf.divide(x, y)
z = x / y
print(f"Dividing {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

# Two ways of element-wise multiplication
z = tf.multiply(x, y)
z = x * y
print(f"Multiplying {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

# Dot-product
z = tf.tensordot(x, y, axes=1)
print(f"The dot product of {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

# Exponentiation
z = x ** 5
print(f"{x.numpy()} raised to the power of 5 gives us {z.numpy()}")

# Matrix multiplication
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))

# Two ways of matrix multiplication
z = tf.matmul(x, y)
z = x @ y
print(f"Matrix multiplication of {x.numpy()} and {y.numpy()} gives us {z.numpy()}")

Adding [1 2 3] and [9 8 7] gives us [10 10 10]
Subtracting [1 2 3] and [9 8 7] gives us [-8 -6 -4]
Dividing [1 2 3] and [9 8 7] gives us [0.11111111 0.25       0.42857143]
Multiplying [1 2 3] and [9 8 7] gives us [ 9 16 21]
The dot product of [1 2 3] and [9 8 7] gives us 46
[1 2 3] raised to the power of 5 gives us [  1  32 243]
Matrix multiplication of [[-0.5834047  -0.9063122  -0.37869352]
 [ 1.5943869   0.12082507  0.8071664 ]] and [[-0.18177246 -0.10304508]
 [-1.1948669  -1.3671743 ]
 [-1.0090032   0.4024466 ]] gives us [[ 1.5710723   1.1467998 ]
 [-1.248619   -0.00464129]]


In [ ]:
# Indexing in a vector
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

# Get values at specific indices in a tensor
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

# Indexing in a matrix
x = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x[0, :])
print(x[0:2, :])

# Reshaping
x = tf.range(9)
x = tf.reshape(x, (3, 3))
x = tf.transpose(x, perm=[1, 0])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Automatic Differentiation

The easiest way to use the automatic differentiation engine is with `tf.GradientTape`.

Suppose we want to find the gradient of a function `func` when given input `x`.
* Call `y = func(x)` in a `with tf.GradientTape() as tape:` block.
* Compute the gradients with `tape.gradient(y, x)`.

For example:


In [ ]:
# This is the function that we want to differentiate.
def func(x):
  return 3*x*x + 2*x

# This is the gradient function computed by-hand.
def manual_grad_func(x):
  return 6*x + 2

# This is the gradient function computed by TF.
def auto_grad_func(x):
  x = tf.Variable(x, dtype=tf.float32)
  with tf.GradientTape() as tape:
    y = func(x)
  return tape.gradient(y, x) 

In [ ]:
x = 1
print(f'x = {x}')
print(f'Expected f\'(x): {manual_grad_func(x)}')
print(f'Computed f\'(x): {auto_grad_func(x)}')

x = 1
Expected f'(x): 8
Computed f'(x): 8.0
